### ISSUE TITLE
Cut-off friend menu

### ISSUE THREAD

**Issue by Azsofe** [Hypnootize/hexhud#1]
When I click on a friend, the menu is cut-off. See the picture.
![20210624211109_1](https://user-images.githubusercontent.com/44698264/123320483-1ad24100-d532-11eb-851f-db55394b5249.jpg)

**Comment by Hypnootize** [comment]
I am aware of that, is a result of me trying to keep the friends list in a single line to match the rest of the menu, I admit I was going more for looks that anything there as I also don't really use the friends list ever. 
I might make a list customization with multiple rows aimed for anyone that does a heavy use of it in the not so distant future.

**Comment by Hypnootize** [comment]
The new extended friendslist should mitigate this problem for the most part, https://github.com/Hypnootize/hexhud/wiki/Friends-List
