### ISSUE TITLE
Spy's Disguise Bug

### ISSUE THREAD

**Issue by XeroDollars** [Hypnootize/hexhud#10]
When you spawn as spy, before you disguise as anyone it will display blu team. After changing disguise it will display it correctly. If you die it will then reset.

**Comment by Hypnootize** [comment]
Sorry for the late answer, I have been trying to re-create this with no success, I assume you mean the top of the disguise menu (https://i.imgur.com/In7F9CW.jpg) shows the wrong team color at first but it doesn't seem to happen for me, everything seems to be using the correct colors.

**Comment by XeroDollars** [comment]
> 

yeah i should have taken this down because its not happening anymore, it was doing it a couple times when i made the post, so im sorry, i guess it was a fluke? idk again really sry for the trouble

**Comment by Hypnootize** [comment]
Oh no worries!
