### ISSUE TITLE
Linux: Fallbacks to default hud (Solved, but useful for the wiki)

### ISSUE THREAD

**Issue by sbritorodr** [Hypnootize/hexhud#13]
In Linux, caps matter a lot.
When I uncompress the folder, if your folder starts with a capital letter, TF2 will ignore it.
It would be cool to add this issue in the wiki

**Comment by Hypnootize** [comment]
I've forgot about this as I meant to re-write most of the wiki eventually but at this point I'm not sure when I will do that. For now I quickly mentioned it under the [common installation issues](https://github.com/Hypnootize/hexhud/wiki/Troubleshoot#common-issues) so if anyone encounters this problem will hopefully see it.
