### ISSUE TITLE
Spells are not visible when disguised as spy

### ISSUE THREAD

**Issue by Wonkglorg** [Hypnootize/hexhud#16]
The spells are behind the disguised spy overlay making them impossible to see

**Comment by Hypnootize** [comment]
It's something I meant to rework for a while but I haven't got it to it yet. 

You can pretty easily reposition it by opening `Resource/UI/HudSpellSelection.res` and editing both `"xpos"` and `"ypos"` at the very [start of the file](https://github.com/Hypnootize/hexhud/blob/master/resource/ui/hudspellselection.res#L5-L6)

**Comment by Wonkglorg** [comment]
Already did that thanks for the reply tho, wanted to bring light to it if it was not known yet

**Comment by Hypnootize** [comment]
Closing as it should no longer be an issue with the last update
