### ISSUE TITLE
Demo shield charge meter design doesn't match other meters (when "Default" style is enabled)

### ISSUE THREAD

**Issue by Kruphixx** [Hypnootize/hexhud#19]
![Screenshot 2024-07-29 002400](https://github.com/user-attachments/assets/cff7fdc5-d221-4f6f-9e11-5e5a24e64b7f)

**Comment by Hypnootize** [comment]
Should be better now, I tried also coloring it with an overlay as you can't use a modulate texture like the other meters but the results aren't really the best, I'll keep it white for now as I doesn't bother me too much.

**Comment by Kruphixx** [comment]
Thank you!
