### ISSUE TITLE
Broken Wiki Link

### ISSUE THREAD

**Issue by paulshuker** [Hypnootize/hexhud#25]
Hey your hud is amazing! One issue I had: the wiki customization link https://github.com/Hypnootize/hexhud/wiki/Health says "You do not have permission to update this wiki." when I try to view it. I wanted to see if there was a way I could move the Ubercharge bar closer to the crosshair. Thanks.

**Comment by Sizzler48** [comment]
tf/custom/hexhud/resource/ui/hudmedicharge_hex.res and edit "UberAnchor", 

Adjust the xpos and ypos values accordingly.

**Comment by Hypnootize** [comment]
The link was actually wrong so GitHub was trying to create a new page instead of sending you to the correct page. Should be good now ty!
