### ISSUE TITLE
Recent TF2 Scream Fortress Update broke the HUD

### ISSUE THREAD

**Issue by KodusTheOnly** [Hypnootize/hexhud#26]
With the most recent update, you can't see the rank from other users while in a match. The party chat font is huge. and the inventory menu is also bigger than before.
This update also broke many other HUDs, but is there a current fix for these bugs?
![Captura de tela 2024-10-12 165252](https://github.com/user-attachments/assets/2bf8d254-f354-4c7d-9ce5-d663d3b6bb18)
![Captura de tela 2024-10-12 1648272](https://github.com/user-attachments/assets/a3fc762e-d575-47f4-9d25-f3a3dadbb4d8)
![Captura de tela 2024-10-12 164733](https://github.com/user-attachments/assets/67ef0aaa-1527-4c14-a112-851fa2c130ad)

**Comment by Sizzler48** [comment]
I believe this is a wide-scale issue from the 2024 Halloween update. Valve added better support for UI scaling based on monitor resolution with the update, but currently broken for most common values (i.e. 1080p). Pretty much every HUD has the issue.

**Comment by Hypnootize** [comment]
Should be fixed with the last commit

**Comment by KodusTheOnly** [comment]
Its working perfectly! Thank you so much!
