### ISSUE TITLE
There is no workshop button

### ISSUE THREAD

**Issue by Duptier** [Hypnootize/hexhud#4]
![image](https://user-images.githubusercontent.com/82429716/124051555-0aedbc00-da60-11eb-9716-4dccce48afd5.png)
The workshop button is nowhere to be found, and only on this HUD specifically. I have tested against Default hud to make sure this isn't a "me" issue, but it exists on default hud. And to be absolutely certain, I also tested on FlawHUD and RaysHud, and the workshop button exists.

Unsure whether this was intentional or not, but I just thought: "better to point it out than to leave it hanging"

**Comment by Hypnootize** [comment]
I didn't add it right away because I feel like almost no one uses the in game workshop nowadays, but I can always add it in the future if there is enough deman!

**Comment by sbritorodr** [comment]
I've added a PR adding that button. You can [download my fork ](https://github.com/sbritorodr/hexhud)if you want to implement it right now, @Duptier .

**Comment by Hypnootize** [comment]
[V1.1](https://github.com/Hypnootize/hexhud/releases/tag/v1.1) features both workshop and replay menus now!
