### ISSUE TITLE
Linux font issues

### ISSUE THREAD

**Issue by DeWolfRobin** [Hypnootize/hexhud#8]
Hi there,

I am using this amazing HUD and I am having some issues on Linux related to the font. These issues are not due to the HUD, as I also have them in the original HUD. The issue is as followed (screenshot from original HUD):
https://imgur.com/a/vGkz6i2

This is because of the whitespace characters I presume. I have changed the chat font inside the "tf/custom/hexhud/resource/chatscheme.res:329" where it says name, I changed this to some native Linux fonts, but the issue remains. any ideas on how to fix this? for example edit the formatting of the chat display (Player: Text they say). Maybe this could solve the issue.

**Comment by Hypnootize** [comment]
Hi,

I have never seen this before. I have been asking around for some more opinions on this, as I'm not 100% sure what could be causing this, but with no success. It does seem like something whitespace related to me as well but I know of many other users no having any issues using Verdana on linux for example, so I'm not sure if it could be something distro maybe.

About the formatting, you might be able to edit some of it by editing the tf_english.txt but you will still be able to see the character appear inbetween the message text.
