### ISSUE TITLE
Hud's Background is all white

### ISSUE THREAD

**Issue by YellowInkling** [Hypnootize/hexhud#9]
Hi I tried installing this hud using the TF2 Hud editor but the background is all white instead of black.

How do i fix this?
![20220315193512_1](https://user-images.githubusercontent.com/74347915/158320677-bfac73a4-00cc-40c7-bdd6-38f6b0efd849.jpg)

**Comment by Hypnootize** [comment]
Hey! Looks like you are also missing some other elements so to me it looks like you might have another mod inside your custom folder that also features a resource/ClientScheme.res file and is interfering with the HUD. 
Another user reported the same exact problem in the past and that was the issue so I would suggeset to start from there and look if you can find any other ClientScheme.res file inside your custom folder.

**Comment by Anubeia** [comment]
I found that this occurred when I installed TF2 Bot Overhaul, so everything checks out.
